language: node_js
#sudo: enabled
before_install: 
  - if [[ `npm -v` != 5* ]]; then npm i -g npm@5.6.0; fi
  
install:
  - sudo add-apt-repository -y ppa:ondrej/php
  - sudo apt update
  - sudo apt-get install -y php7.0 php7.0-mbstring php7.0-xml

# Install Image and Video/GIF Manipulation Tools
  - sudo add-apt-repository -y ppa:mc3man/trusty-media
  - sudo add-apt-repository -y ppa:jamedjo/ppa
  - sudo apt-get update
  - sudo apt-get install -y ffmpeg imagemagick pngquant gifsicle webp


# Install Node.js (note you may need to uninstall it first for this to work)
#   - curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
#  - sudo apt-get install -y nodejs

# Install Node packages
  - npm install
  
script:
  - make
